export const AppStrings ={
    APP_NAME:'txt2plate',
    EMAIL_ERROR:'Invalid email',
    PASSWORD_ERROR:'Invalid password',
    PASSWORD_ERROR_MIN:'Password shoud be at lest 6 characters!',
    FIELD_REQUIRED:'required',
    PASSWORD_MATCH:'Password not match!',
    TOC_ERROR:' Terms and conditions page must be read before you can register',
    LOGIN_TEXT:"To keep connect with us Pease login with your \n personal \n information by emai address and password",
    LICENSE_TEXT:"Tag that license plate now and get them noticed!",
    CREDENTIALS_EEOR:"Invalid credentials",
    WRONG_TEXT:"Something went wrong",
    BLOCK_DESIVCE:"We have blocked all requests from this device due to unusual activity",
    EMAIL_VERFICATION_TEXT:"An email verification link has been sent to your email. Please check your inbox and verify your email before logging in.",
    SEND_MESSAGE_TEXT:"SEND YOUR MESSAGE TO THE VEHICLE OWNER!",
    REPLY_TEXT:"DO YOU WANT TO ALLOW A REPLY TO YOUR MESSAGE?",
    USER_EXIST:"Username already exists",
    VEHICLE:"Vehicle number already exists",
    CHOOSE_FILE:"Choose file'",
    NO_FILE_SELECTED:"no file selected'",
}